export enum SportType {
  PADEL = 'padel',
  TENNIS = 'tennis',
  FOOTBALL = 'football',
  BASKETBALL = 'basketball',
  VOLLEYBALL = 'volleyball',
  BADMINTON = 'badminton',
  TABLE_TENNIS = 'table_tennis',
  SQUASH = 'squash',
  SWIMMING = 'swimming',
  BILLIARDS = 'billiards',
  BOWLING = 'bowling',
  GAMING = 'gaming',
  VR = 'vr',
  ESCAPE_ROOM = 'escape_room',
  BOARD_GAMES = 'board_games',
  OTHER = 'other',
}
